"""empty message

Revision ID: df599e69e243
Revises: 
Create Date: 2025-02-03 15:18:30.141007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df599e69e243'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('budgets')
    op.drop_table('statements')
    op.drop_table('transactions')
    op.drop_table('expenses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('expense_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('budget_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('expense_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.budget_id'], name='expenses_budget_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expense_id', name='expenses_pkey')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=24), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('statement_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('credit', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('service_charge', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('change', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['statement_name', 'user_id'], ['statements.statement_name', 'statements.user_id'], name='trans_state_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='trans_users_fk'),
    sa.PrimaryKeyConstraint('transaction_id', name='transactions_pkey')
    )
    op.create_table('statements',
    sa.Column('statement_name', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('running_balance', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False),
    sa.Column('running_credits', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('running_debits', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('running_charges', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('num_transactions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bank', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('initial_balance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='state_users_fk'),
    sa.PrimaryKeyConstraint('statement_name', 'user_id', name='statements_pk')
    )
    op.create_table('budgets',
    sa.Column('user_id', sa.VARCHAR(length=24), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('budget_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='budgets_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('budget_id', name='budgets_pkey')
    )
    op.create_table('users',
    sa.Column('user_id', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey')
    )
    # ### end Alembic commands ###
